### ISSUE TITLE
Drill timer issue

### ISSUE THREAD

**Issue by LT71** [steam-test1/PD2Mods#4]
There seems to be a weird bug with unbreakable drills. So for example the drills you use on bomb forest, golden grins metal gates and on the containers in bomb dockyard eyc. If you place a drill on these types and then for example saw it open or use keys the drill timer will be stuck on the screen with whatever value it had when it was sawed open.

This only happens with those drills, normal drills on other heists work just fine and goes away when saved etc

**Comment by steam-test1** [comment]
The problem is the code/mod needs a rewrite, but it's a low priority at the moment

**Comment by LT71** [comment]
Since it's such a specific condition problem in a rare scenario I'm just gonna go ahead and close this
